apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test
  description: test API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/mohankumarss/my-backstage-app/blob/main/api/result.yml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
definition:
    $text: result.yml