apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test
  description: test API
  tags:
    - test
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition:
    $text: ./result.yaml